#index:
#    path: /
#    controller: App\Controller\DefaultController::index

updateDataAndInformBot:
    path: /updateDataAndInformBot
    controller: App\Controller\DefaultController::updateDataAndInformBot
